name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 1

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose


  publish:
    needs: release

    runs-on: ubuntu-latest

    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 1

      - name: Publish
        run: cargo publish